import type { NewsArticle, AITool, OpenSourceRepo, SAPUpdate } from './types';

export const newsArticles: NewsArticle[] = [
  {
    id: '1',
    slug: 'gpt-5-technical-preview-released',
    title: 'GPT-5 Technical Preview: Extended Context Window & Reasoning Breakthroughs',
    summary:
      'OpenAI quietly dropped the technical preview of GPT-5, featuring a 2M-token context window and unprecedented multi-step reasoning chains. Early benchmarks show a 40% improvement on MMLU and GPQA compared to GPT-4o.',
    category: 'Model Release',
    source: 'OpenAI Blog',
    sourceUrl: '#',
    publishedAt: '2026-03-13T08:00:00Z',
    readTime: 6,
    tags: ['GPT-5', 'OpenAI', 'LLM', 'Reasoning'],
    featured: true,
    imageGradient: 'from-violet-900/60 via-violet-800/40 to-surface-950',
  },
  {
    id: '2',
    slug: 'anthropic-claude-4-benchmarks',
    title: 'Claude 4 Sets New Bars in Code Gen and Instruction Following',
    summary:
      'Anthropic released Claude 4 Sonnet and Claude 4 Opus, claiming top positions on SWE-bench Verified and the LMSYS Chatbot Arena. The new 200K context model introduces improved "extended thinking" for complex multi-hop queries.',
    category: 'Model Release',
    source: 'Anthropic',
    sourceUrl: '#',
    publishedAt: '2026-03-13T06:30:00Z',
    readTime: 5,
    tags: ['Claude 4', 'Anthropic', 'Code Generation', 'Benchmarks'],
    imageGradient: 'from-orange-900/60 via-orange-800/40 to-surface-950',
  },
  {
    id: '3',
    slug: 'google-deepmind-gemini-ultra-2',
    title: 'DeepMind Unveils Gemini Ultra 2 with Native Multimodal Reasoning',
    summary:
      'Google DeepMind announced Gemini Ultra 2, adding native video-in, audio-out capabilities. The model demonstrates real-time embodied reasoning in robotics tasks and introduces a new "Flash Thinking" mode for latency-critical apps.',
    category: 'Model Release',
    source: 'Google DeepMind',
    sourceUrl: '#',
    publishedAt: '2026-03-12T14:00:00Z',
    readTime: 7,
    tags: ['Gemini', 'Google', 'Multimodal', 'Robotics'],
    imageGradient: 'from-blue-900/60 via-blue-800/40 to-surface-950',
  },
  {
    id: '4',
    slug: 'meta-llama-4-open-source',
    title: "Meta's Llama 4 Goes Open Source: 70B and 405B Models Available Now",
    summary:
      'Meta open-sourced Llama 4 under a commercial-friendly license. The 70B variant outperforms GPT-4o on coding tasks while the 405B MoE reaches near-frontier quality. Both models support a 128K context window out of the box.',
    category: 'Open Source',
    source: 'Meta AI',
    sourceUrl: '#',
    publishedAt: '2026-03-12T10:00:00Z',
    readTime: 5,
    tags: ['Llama 4', 'Meta', 'Open Source', 'MoE'],
    imageGradient: 'from-emerald-900/60 via-emerald-800/40 to-surface-950',
  },
  {
    id: '5',
    slug: 'openai-o3-mini-release',
    title: 'OpenAI Releases o3-mini: Frontier Reasoning at 60% Lower Cost',
    summary:
      'OpenAI\'s o3-mini brings the o3 reasoning capabilities to a smaller, faster, and significantly cheaper package. It matches o3-full performance on math olympiad problems while running 4x faster—ideal for production agentic systems.',
    category: 'Model Release',
    source: 'OpenAI',
    sourceUrl: '#',
    publishedAt: '2026-03-11T18:00:00Z',
    readTime: 4,
    tags: ['o3-mini', 'OpenAI', 'Reasoning', 'Cost'],
    imageGradient: 'from-cyan-900/60 via-cyan-800/40 to-surface-950',
  },
  {
    id: '6',
    slug: 'mistral-codestral-2-5',
    title: 'Mistral Drops Codestral 2.5: Tops HumanEval, Beats GPT-4o on Code',
    summary:
      'Mistral AI released Codestral 2.5, a code-specialized model that achieves 94.3% on HumanEval and 72.1% on SWE-bench. It supports fill-in-the-middle completion for 30+ programming languages and a 256K FIM context.',
    category: 'Model Release',
    source: 'Mistral AI',
    sourceUrl: '#',
    publishedAt: '2026-03-11T12:00:00Z',
    readTime: 4,
    tags: ['Codestral', 'Mistral', 'Code', 'HumanEval'],
    imageGradient: 'from-rose-900/60 via-rose-800/40 to-surface-950',
  },
  {
    id: '7',
    slug: 'chain-of-thought-structured-output',
    title: 'Research: Structured Output Boosts CoT Performance by 40%',
    summary:
      'A new paper from Stanford and MIT shows that enforcing JSON or XML structured outputs during chain-of-thought reasoning dramatically reduces hallucination rates and improves accuracy on multi-hop QA benchmarks by up to 40%.',
    category: 'Research',
    source: 'arXiv',
    sourceUrl: '#',
    publishedAt: '2026-03-11T08:00:00Z',
    readTime: 8,
    tags: ['CoT', 'Structured Output', 'Research', 'Hallucination'],
    imageGradient: 'from-indigo-900/60 via-indigo-800/40 to-surface-950',
  },
  {
    id: '8',
    slug: 'hugging-face-smollm3',
    title: 'Hugging Face Launches SmolLM3: SOTA 3B Model for Edge & Mobile',
    summary:
      'HuggingFace released SmolLM3, a 3-billion parameter model that beats Phi-3.8B and Gemma-3B on most benchmarks while fitting in 4GB RAM. It supports tool-use natively and runs locally on M-series Macs and Android devices.',
    category: 'Open Source',
    source: 'Hugging Face',
    sourceUrl: '#',
    publishedAt: '2026-03-10T16:00:00Z',
    readTime: 5,
    tags: ['SmolLM', 'HuggingFace', 'Edge AI', 'On-device'],
    imageGradient: 'from-yellow-900/60 via-yellow-800/40 to-surface-950',
  },
  {
    id: '9',
    slug: 'microsoft-copilot-studio-azure',
    title: 'Microsoft Copilot Studio Supports Custom Models via Azure AI Foundry',
    summary:
      'Microsoft extended Copilot Studio to allow enterprises to plug in custom fine-tuned models via Azure AI Foundry. This enables organizations to deploy proprietary models in M365 workflows without exposing data to third-party providers.',
    category: 'Industry',
    source: 'Microsoft Tech Blog',
    sourceUrl: '#',
    publishedAt: '2026-03-10T10:00:00Z',
    readTime: 4,
    tags: ['Microsoft', 'Copilot', 'Azure', 'Enterprise'],
    imageGradient: 'from-sky-900/60 via-sky-800/40 to-surface-950',
  },
  {
    id: '10',
    slug: 'stanford-hai-enterprise-ai-report',
    title: 'Stanford HAI Report: Enterprise AI Adoption Doubles in 12 Months',
    summary:
      'The annual Stanford Human-Centered AI report reveals enterprise AI adoption doubled year-over-year, with 78% of Fortune 500 companies deploying at least one generative AI system in production. Productivity gains average 23% in knowledge work.',
    category: 'Industry',
    source: 'Stanford HAI',
    sourceUrl: '#',
    publishedAt: '2026-03-09T12:00:00Z',
    readTime: 9,
    tags: ['Enterprise AI', 'Research', 'Adoption', 'Productivity'],
    imageGradient: 'from-purple-900/60 via-purple-800/40 to-surface-950',
  },
  {
    id: '11',
    slug: 'pytorch-2-6-release',
    title: 'PyTorch 2.6 Released: 3x Faster Compilation, New Flex Attention API',
    summary:
      'Meta\'s PyTorch 2.6 ships with torch.compile 3x faster cold-start times, a new FlexAttention API for custom attention kernels, and experimental support for AMD ROCm 6.2. The release also adds native FP8 training support.',
    category: 'Framework',
    source: 'PyTorch Blog',
    sourceUrl: '#',
    publishedAt: '2026-03-09T08:00:00Z',
    readTime: 5,
    tags: ['PyTorch', 'Framework', 'Performance', 'Attention'],
    imageGradient: 'from-orange-900/60 via-red-900/40 to-surface-950',
  },
  {
    id: '12',
    slug: 'anthropic-model-spec-update',
    title: 'Anthropic Updates Model Spec: Constitutional AI 2.0 with Steering Capabilities',
    summary:
      'Anthropic published an updated Model Spec introducing Constitutional AI 2.0—a framework for steering model behavior at inference time using structured principles. The update enables deployment teams to customize safety thresholds per use case.',
    category: 'Research',
    source: 'Anthropic',
    sourceUrl: '#',
    publishedAt: '2026-03-08T14:00:00Z',
    readTime: 7,
    tags: ['Constitutional AI', 'Anthropic', 'Safety', 'Alignment'],
    imageGradient: 'from-teal-900/60 via-teal-800/40 to-surface-950',
  },
];

export const aiTools: AITool[] = [
  {
    id: '1',
    name: 'Cursor',
    tagline: 'The AI-first code editor',
    description:
      'Cursor is a fork of VS Code with deep AI integration. Write, edit, and chat about code with GPT-4 and Claude. Its Composer mode lets you make multi-file edits from natural language.',
    category: 'Developer Tools',
    platform: ['Desktop'],
    launchDate: '2026-03-10',
    upvotes: 4820,
    url: 'https://cursor.com',
    tags: ['Code Editor', 'AI Coding', 'VS Code', 'Pair Programming'],
    isNew: true,
    isFeatured: true,
    accentColor: '#7c3aed',
  },
  {
    id: '2',
    name: 'Dify.ai',
    tagline: 'Open-source LLM app builder',
    description:
      'Dify is a visual LLM application development platform. Build, test, and deploy AI workflows with RAG, agents, and model management — no code required for most use cases.',
    category: 'AI Platform',
    platform: ['Web', 'Open Source'],
    launchDate: '2026-03-08',
    upvotes: 3240,
    url: 'https://dify.ai',
    tags: ['RAG', 'Agent Builder', 'No-Code', 'Workflow'],
    isNew: true,
    accentColor: '#06b6d4',
  },
  {
    id: '3',
    name: 'Langfuse',
    tagline: 'Open-source LLM observability',
    description:
      'Langfuse provides traces, evals, prompt management, and metrics for LLM-powered applications. Drop-in SDK for OpenAI, LangChain, and LlamaIndex.',
    category: 'Observability',
    platform: ['API', 'Open Source'],
    launchDate: '2026-03-07',
    upvotes: 2180,
    url: 'https://langfuse.com',
    tags: ['Observability', 'Tracing', 'Eval', 'LangChain'],
    accentColor: '#10b981',
  },
  {
    id: '4',
    name: 'Bolt.new',
    tagline: 'AI-powered full-stack web builder',
    description:
      'Bolt.new by StackBlitz lets you prompt, run, edit, and deploy full-stack web apps directly in your browser. Powered by Claude Sonnet with instant preview environments.',
    category: 'Web Builder',
    platform: ['Web'],
    launchDate: '2026-03-05',
    upvotes: 5610,
    url: 'https://bolt.new',
    tags: ['Web Builder', 'Full Stack', 'No-Code', 'Deployment'],
    accentColor: '#f97316',
  },
  {
    id: '5',
    name: 'AnythingLLM',
    tagline: 'Private, self-hosted AI workspace',
    description:
      'AnythingLLM is a fully private AI workspace that connects to any LLM, vector DB, or document store. Deploy locally or to your own cloud with zero data leaving your environment.',
    category: 'AI Workspace',
    platform: ['Desktop', 'Open Source'],
    launchDate: '2026-03-04',
    upvotes: 1890,
    url: 'https://anythingllm.com',
    tags: ['Privacy', 'Self-hosted', 'RAG', 'Local LLM'],
    accentColor: '#4f46e5',
  },
  {
    id: '6',
    name: 'v0 by Vercel',
    tagline: 'Generate UI with AI',
    description:
      'v0 generates copy-paste friendly React + Tailwind UI from plain text descriptions. Supports shadcn/ui, responsive layouts, and dark mode. New: edit components with natural language.',
    category: 'UI Generation',
    platform: ['Web', 'API'],
    launchDate: '2026-03-03',
    upvotes: 3450,
    url: 'https://v0.dev',
    tags: ['UI', 'React', 'Tailwind', 'Code Gen'],
    accentColor: '#f43f5e',
  },
  {
    id: '7',
    name: 'Perplexity Pro',
    tagline: 'AI-powered answer engine',
    description:
      'Perplexity Pro offers GPT-4o, Claude 3.5, and Sonar models with real-time web search, deep research mode, and file upload. New Spaces feature enables team knowledge management.',
    category: 'AI Search',
    platform: ['Web', 'API'],
    launchDate: '2026-03-01',
    upvotes: 4200,
    url: 'https://perplexity.ai',
    tags: ['Search', 'Research', 'Web', 'Knowledge'],
    accentColor: '#06b6d4',
  },
  {
    id: '8',
    name: 'Replit AI Agent',
    tagline: 'Autonomous coding agent in the cloud',
    description:
      'Replit Agent can plan, scaffold, debug, and deploy full applications autonomously. Point it at a requirement and watch it build — supports 50+ languages in an always-on cloud IDE.',
    category: 'AI Agent',
    platform: ['Web'],
    launchDate: '2026-02-28',
    upvotes: 2760,
    url: 'https://replit.com',
    tags: ['Agent', 'Cloud IDE', 'Deployment', 'Autonomous'],
    accentColor: '#a78bfa',
  },
];

export const openSourceRepos: OpenSourceRepo[] = [
  {
    id: '1',
    name: 'ollama',
    owner: 'ollama',
    description: 'Get up and running with large language models locally. Supports Llama 4, Mistral, DeepSeek, Gemma and dozens more.',
    language: 'Go',
    languageColor: '#00ADD8',
    stars: 128400,
    forks: 10200,
    starsToday: 842,
    category: 'Local LLM',
    tags: ['Local AI', 'LLM Runtime', 'CLI', 'Self-hosted'],
    url: '#',
    lastUpdated: '2026-03-13',
    license: 'MIT',
  },
  {
    id: '2',
    name: 'llama.cpp',
    owner: 'ggerganov',
    description: 'LLM inference in C/C++. Quantized models for CPU inference. The backbone of most local AI tooling.',
    language: 'C++',
    languageColor: '#f34b7d',
    stars: 74800,
    forks: 10700,
    starsToday: 412,
    category: 'LLM Inference',
    tags: ['Inference', 'GGUF', 'CPU', 'Quantization'],
    url: '#',
    lastUpdated: '2026-03-13',
    license: 'MIT',
  },
  {
    id: '3',
    name: 'ai',
    owner: 'vercel',
    description: 'The AI SDK by Vercel. Build AI-powered streaming text and chat UIs in React, Next.js, Vue, Svelte, and Node.',
    language: 'TypeScript',
    languageColor: '#3178c6',
    stars: 13800,
    forks: 1920,
    starsToday: 318,
    category: 'AI SDK',
    tags: ['TypeScript', 'React', 'Streaming', 'Chat UI'],
    url: '#',
    lastUpdated: '2026-03-12',
    license: 'Apache-2.0',
  },
  {
    id: '4',
    name: 'autogen',
    owner: 'microsoft',
    description: 'A framework for building LLM-based multi-agent applications. Enable complex orchestration patterns between AI agents.',
    language: 'Python',
    languageColor: '#3572A5',
    stars: 38900,
    forks: 5600,
    starsToday: 276,
    category: 'Multi-Agent',
    tags: ['Agents', 'Orchestration', 'Multi-Agent', 'Python'],
    url: '#',
    lastUpdated: '2026-03-12',
    license: 'CC-BY-4.0',
  },
  {
    id: '5',
    name: 'langchain',
    owner: 'langchain-ai',
    description: 'Build context-aware reasoning applications using LangChain. Composable primitives for RAG, agents, chains, and memory.',
    language: 'Python',
    languageColor: '#3572A5',
    stars: 97200,
    forks: 16100,
    starsToday: 198,
    category: 'LLM Framework',
    tags: ['RAG', 'Agents', 'Framework', 'Chains'],
    url: '#',
    lastUpdated: '2026-03-11',
    license: 'MIT',
  },
  {
    id: '6',
    name: 'open-webui',
    owner: 'open-webui',
    description: 'User-friendly web interface for AI. Works with Ollama, OpenAI, and custom backends. Rich plugin ecosystem.',
    language: 'Python',
    languageColor: '#3572A5',
    stars: 49700,
    forks: 6100,
    starsToday: 521,
    category: 'AI UI',
    tags: ['Web UI', 'Chat', 'Ollama', 'Self-hosted'],
    url: '#',
    lastUpdated: '2026-03-13',
    license: 'MIT',
  },
];

export const sapUpdates: SAPUpdate[] = [
  {
    id: '1',
    title: 'SAP Joule v3.2: Cross-Application AI Assistant Now Generally Available',
    summary:
      'Joule v3.2 introduces cross-app AI orchestration across S/4HANA, SuccessFactors, Ariba, and Concur in a single conversation thread. The new Joule Studio lets customers build custom Joule skills using BTP.',
    product: 'Joule',
    updateType: 'Release',
    publishedAt: '2026-03-13T09:00:00Z',
    sourceUrl: '#',
    isNew: true,
    tags: ['Joule', 'S/4HANA', 'BTP', 'Cross-App'],
  },
  {
    id: '2',
    title: 'SAP AI Core: Claude 3.5 Sonnet & Llama 4 Now Available in Generative AI Hub',
    summary:
      'SAP expanded the Generative AI Hub model roster in SAP AI Core, adding Anthropic Claude 3.5 Sonnet, Meta Llama 4, and Mistral Large 2. Customers can now benchmark and switch models from the AI Core cockpit.',
    product: 'Generative AI Hub',
    updateType: 'Feature',
    publishedAt: '2026-03-12T14:00:00Z',
    sourceUrl: '#',
    isNew: true,
    tags: ['Generative AI Hub', 'Claude', 'Llama', 'Model Roster'],
  },
  {
    id: '3',
    title: 'SAP Business AI: Intelligent Invoice Processing Hits 98% Accuracy',
    summary:
      'SAP\'s Intelligent Invoice Processing powered by Business AI now reports 98% accuracy on unstructured PDF invoices, up from 92% in Q4 2025. The improvement is attributed to a new fine-tuned document understanding model.',
    product: 'Business AI',
    updateType: 'Announcement',
    publishedAt: '2026-03-12T10:00:00Z',
    sourceUrl: '#',
    isNew: true,
    tags: ['Invoice Processing', 'Document AI', 'Accuracy', 'Finance'],
  },
  {
    id: '4',
    title: 'SAP AI Core: Vector Engine Integration with SAP HANA Cloud GA',
    summary:
      'SAP AI Core now natively integrates with SAP HANA Cloud\'s vector engine for RAG-based enterprise AI applications. Customers can ground Generative AI Hub models on structured and unstructured SAP data without ETL pipelines.',
    product: 'AI Core',
    updateType: 'Feature',
    publishedAt: '2026-03-11T16:00:00Z',
    sourceUrl: '#',
    tags: ['Vector Engine', 'HANA Cloud', 'RAG', 'Grounding'],
  },
  {
    id: '5',
    title: 'Weekly SAP AI Digest — Week of March 10, 2026',
    summary:
      'This week in SAP AI: Joule v3.2 GA, Generative AI Hub model expansion, HANA Vector Engine integration, and Joule for SuccessFactors new hire onboarding workflows. Plus TechEd 2026 AI track preview.',
    product: 'Community',
    updateType: 'Deep Dive',
    publishedAt: '2026-03-10T08:00:00Z',
    sourceUrl: '#',
    isWeeklyDigest: true,
    tags: ['Weekly Digest', 'SAP AI', 'Summary'],
  },
  {
    id: '6',
    title: 'Joule for HR: New Onboarding & Workforce Planning Workflows in SuccessFactors',
    summary:
      'SAP embedded Joule deeply into SuccessFactors, adding AI-powered onboarding task automation, workforce planning recommendations, and skills gap analysis. HR teams can now trigger multi-step processes via natural language.',
    product: 'Joule',
    updateType: 'Feature',
    publishedAt: '2026-03-09T14:00:00Z',
    sourceUrl: '#',
    tags: ['SuccessFactors', 'HR AI', 'Onboarding', 'Workforce Planning'],
  },
  {
    id: '7',
    title: 'SAP TechEd 2026: AI Core Roadmap Revealed — Agentic AI & Multi-Model Routing',
    summary:
      'At SAP TechEd 2026, the AI Core team previewed the H2 roadmap including agentic AI orchestration, intelligent model routing based on task complexity and cost, and a new AI Core Python SDK for developer teams.',
    product: 'AI Core',
    updateType: 'Announcement',
    publishedAt: '2026-03-08T18:00:00Z',
    sourceUrl: '#',
    tags: ['TechEd', 'Roadmap', 'Agentic AI', 'Model Routing'],
  },
  {
    id: '8',
    title: 'SAP Community: Top AI Questions This Week — Joule API, HANA Vector, AI Core Setup',
    summary:
      'Most active SAP AI community threads this week covered Joule custom skill development via API, HANA Cloud vector store setup, AI Core multi-model deployment patterns, and prompt engineering tips for Generative AI Hub.',
    product: 'Community',
    updateType: 'Community',
    publishedAt: '2026-03-07T12:00:00Z',
    sourceUrl: '#',
    tags: ['Community', 'Q&A', 'Joule API', 'HANA Vector'],
  },
];

export const trendingTopics = [
  { label: 'GPT-5 Release', count: 48 },
  { label: 'Joule v3.2 GA', count: 32 },
  { label: 'Llama 4 Open Source', count: 29 },
  { label: 'AI Agents', count: 27 },
  { label: 'o3-mini Pricing', count: 22 },
  { label: 'HANA Vector Engine', count: 18 },
  { label: 'Edge AI Inference', count: 15 },
  { label: 'Constitutional AI 2.0', count: 14 },
];

export const tickerItems = [
  '🔥 GPT-5 technical preview drops — 2M token context window confirmed',
  '🚀 Meta open-sources Llama 4 405B — available on Hugging Face now',
  '📊 Anthropic Claude 4 tops SWE-bench Verified with 72.4% solve rate',
  '🟢 SAP Joule v3.2 GA — cross-app AI assistant for all SAP products',
  '⚡ Mistral Codestral 2.5 beats GPT-4o on HumanEval with 94.3%',
  '🔬 Stanford HAI: enterprise AI adoption doubled year-over-year',
  '🌐 SAP Generative AI Hub adds Claude 3.5 Sonnet & Llama 4',
  '💡 PyTorch 2.6 ships with 3x faster torch.compile cold-start',
];
